import Head from 'next/head';
import { useQuery } from 'urql';
import { PRODUCT_QUERY } from "../lib/query";
import { Gallery } from '../styles/Gallery';
import { MeiliSearch } from 'meilisearch';
import { useEffect, useState } from "react";
import { ProductStyles , ProgressBarStyles } from "../styles/ProductStyle";
import Link from "next/link";
import Image from 'next/image';
const {  motion , useScroll} = require("framer-motion");



const searchClient = new MeiliSearch({
  host: `${ process.env.NEXT_PUBLIC_MEILISEARCH_HOST }`,
  apiKey: `${ process.env.NEXT_PUBLIC_MEILI_APIKEY }`, // Use the public key not the private or master key to search.
})

export default function Home() {
  //Fetch products from strapi
  const [results] = useQuery({query: PRODUCT_QUERY});
  const {data, fetching, error} = results;
  const [items, setItems] = useState([]);
  const [search, setSearch] = useState("");
  const { scrollYProgress, scrollRef } = useScroll();
  

  useEffect(() => {
    //search product index based on search value
    searchClient
    .index("product")
    .search(search)
    .then((searchResults) => {
      setItems(searchResults.hits);
      const srcResults = searchResults;
    });
  }, [search]);
  
  //Check for the data coming in
  if(fetching) return <p>Loading...</p>;
  if(error) return <p>Oh no...{error.message}</p>;
  const products = data.products.data;
  console.log(items);

  return (
    <div>
      <Head>
        <title>EcoWorld Homepage</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>
        <div className="App">
          <ProgressBarStyles>
              <motion.div
                className="progress-bar "
                style={{ scaleX: scrollYProgress }}
                whileInView={{ opacity: 0.6 }}
              />
           
          <div className="search">
            <input
              type="text"
              value={search}
              placeholder="Search..."
                onChange={(e) => setSearch(e.target.value)}
                className="search2"
            />
            </div>
            </ProgressBarStyles>
        </div>
        <Gallery>
          {items.map((product) => (
          <ProductStyles>
              <Link href={`product/${product.slug}`}>
                
                <motion.div whileHover={{ scale: 1.1 }} className="container">
              <Image 
              src={product.image.data.attributes.formats.medium.url}
              alt={product.title}
              width={200}
              height={200}
                    unoptimized={true}
                    className="image"
                  />
                  <div class="middle">
    <div class="text">Add to Cart</div>
  </div>
                  </motion.div>
            </Link>
            <h2>{product.title}</h2>
            <h3>$ {product.price}</h3>
          </ProductStyles>
          ))}
        </Gallery>
      </main>      
    </div>
  )/* ,
  console.log(products); */
}